### ISSUE TITLE
Multiple sqlite database files

### ISSUE THREAD

**Issue by HarelM** [msallin/SQLiteCodeFirst#22] opened 2015-04-15 11:43 UTC
Hi,

Lets assume I want to use a sqlite database file per user. i.e. user1.db and user2.db files, both with the same schema.
I have created a context with the following constructor

``` cs
public FootballDbContext(string dbFilePath)
            : base(new SQLiteConnection { ConnectionString = new SQLiteConnectionStringBuilder { DataSource = dbFilePath, ForeignKeys = true, DefaultTimeout = 2 }.ConnectionString }, true)
{
    Configuration.ProxyCreationEnabled = true;
    Configuration.LazyLoadingEnabled = true;
}
```

This will allow me to pass the filePath to the constructor of the context.
The problem I'm facing is that both contexts are referring to the same file although they use different connection strings.

What should I do? Is there a workaround or is this a limitation of EF?

**Comment by HarelM** [comment] 2015-04-15 15:12
Ok, I managed to find a workaround and it looks like it is working. not sure what to do with it, so here is the `FootballDbContext` after my changes:
If you have other suggestions/best known method - let me know.

``` cs
    public class FootballDbContext : DbContext
    {
        private static DbModelBuilder dbModelBuilder = null;

        public DbSet<Team> Teams { get; set; }
        public DbSet<Stadion> Stadioms { get; set; }
        public DbSet<Player> Players { get; set; }

        public FootballDbContext(string dbFilePath)
            : base(new SQLiteConnection
            {
                ConnectionString = new SQLiteConnectionStringBuilder { DataSource = dbFilePath, ForeignKeys = true, DefaultTimeout = 2 }.ConnectionString,
            }, true)
        {
            Configuration.ProxyCreationEnabled = true;
            Configuration.LazyLoadingEnabled = true;
            if (dbModelBuilder != null)
            {
                var initializer = new SqliteCreateDatabaseIfNotExists<FootballDbContext>(Database.Connection.ConnectionString, dbModelBuilder);
                Database.SetInitializer(initializer);
                Database.Initialize(false);
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            dbModelBuilder = modelBuilder;
            var initializer = new SqliteCreateDatabaseIfNotExists<FootballDbContext>(Database.Connection.ConnectionString, modelBuilder);
            Database.SetInitializer(initializer);
        }
    }
```

**Comment by msallin** [comment] 2015-04-15 16:03
The root of the problem is, that OnModelCreating will only be called once.
That means no new initializer will be created. So the initializer will try to delete the first database when creating a second context with a different connection string.

I was already able to fix this bug. See branch "[Issue_22](https://github.com/msallin/SQLiteCodeFirst/tree/Issue_22)" for more information.

This will result in a breaking change because the initializers will no longer take connectionString as constructor parameter. But its > v1 so its okay ;)

I'll ship this bugfix with [v0.9.5.1](https://github.com/msallin/SQLiteCodeFirst/milestones/v0.9.5.1).
If you need this fix earlier you can grap the dll from the CI Build artifacts [here](https://ci.appveyor.com/project/msallin/sqlitecodefirst/build/artifacts).

**Comment by HarelM** [comment] 2015-04-16 06:43
I've just tested it, Thanks a lot for the quick response and fix!
Harel M.

**Comment by HarelM** [comment] 2015-04-19 12:02
BTW, other initializers do not require the model builder as a parameter and thus can be configured once when the application starts or in the context's static constructor.
for example when using sql server with migrations and you want the database scheme to update you would use:
`Database.SetInitializer(new MigrateDatabaseToLatestVersion<SomeContext, SomeConfiguration>());`
on the application startup.
Please consider. :-)

Thanks,
Harel M.

**Comment by HarelM** [comment] 2015-04-29 15:55
It appears I have found another scenario where your solution does not help :-(
steps to reproduce:
1. creata a context.
2. dispose of this context.
3. delete the database file.
4. create a context pointing to the same file.
tables are not generated :-( any query to the database will fail.

I'm not sure but I think my workaround still works to this scenrio as well.
Harel M.

**Comment by msallin** [comment] 2015-05-01 12:59
Do you mean the workaround or the code in the [Issue_22](https://github.com/msallin/SQLiteCodeFirst/tree/Issue_22) branch?

**Comment by HarelM** [comment] 2015-05-01 22:22
The code in issue_22 branch does not work for the above scenario. the workaround does but looks bad...

**Comment by msallin** [comment] 2015-07-12 08:53
The partial fix for this is in the master branch.
Its very complicated to support your scenario because the code does not use the same approach as the other initializers.
I'll target this issue as part of #4.

**Closed as completed by msallin** 2015-07-12 08:53 UTC
Labels: bug
