### ISSUE TITLE
{"SQL logic error or missing database\r\nno such table: Servers"}

### ISSUE THREAD

**Issue by phspies** [msallin/SQLiteCodeFirst#53] opened 2015-12-10 22:00 UTC
I'm trying to use this great library and I just cannot get the tables created at startup. The SQLite file is created, but with a 0 size. 

Any ideas why?

This is my DB context code:

```
        public DB()

        : base("DB")
        {
            //Configuration.ProxyCreationEnabled = true;
            //Configuration.LazyLoadingEnabled = true;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            ConfigureCredentialEntity(modelBuilder);
            ConfigurePlatformEntity(modelBuilder);
            ConfigureServerEntity(modelBuilder);

            var sqliteConnectionInitializer = new SqliteCreateDatabaseIfNotExists<CloudMoveyEntities>(modelBuilder);

            Database.SetInitializer(sqliteConnectionInitializer);
        }
```

and 

```
    public partial class DB : DbContext
    {
        private static void ConfigureCredentialEntity(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Credential>().HasKey(p => p.id);
        }
        private static void ConfigurePlatformEntity(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Platform>().HasKey(p => p.id);
        }
        private static void ConfigureServerEntity(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Server>().HasKey(p => p.id);
        }
    }

```

**Comment by msallin** [comment] 2015-12-11 10:21
Which version do you use? This should be fixed with v1.0.0.0 (see issue #43).
Did you try to delete the empty file and run the application again?
If you are using the newest version and the issue persists, can you please send me the whole project?

**Comment by phspies** [comment] 2015-12-11 16:40
Marc,

Thank you very much for responding...I did try to delete the empty file and I am using v1.0.0.0.

I'll add you to the Github repo where the project is.

Regards

**Comment by msallin** [comment] 2015-12-13 12:28
I had a look at your code. I created a Console Project to reproduce the issue.
But I'm not able not find a class "Server". I took the classes From "Sqlite\Structures" and  created a DbContext with the code you posted in the issue description.

May you can help me with creating a project to reproduce this issue?
You can download the Console Project here:
https://onedrive.live.com/redir?resid=C8E1BE3E79378699!523889&authkey=!ABUB4-pZYfcgYhw&ithint=file%2czip

**Comment by msallin** [comment] 2016-01-15 13:37
Closed because auf inactivity.
Please reopen it, if additional actions are required.

**Closed as completed by msallin** 2016-01-15 13:37 UTC
Labels: To Analyse

**Comment by Clockwork-Muse** [comment] 2017-09-20 18:54
Given my current experience, one reason this can happen is if there's an explicit call to `context.Database.Connection.Open()`  preceding EF initalization, that is, before the initializer is run.  (Why?  I dunno - this is maybe something to bring up with the SQLite people).  I can't dodge the explicit call in my case (I have multiple concurrent transactions), so getting the context and just asking for `Any` on one of the relationships during process setup is what I have to do.  Commands to `CREATE TABLE` run just fine (no exception is thrown), but seem to have no effect in the db
