### ISSUE TITLE
Data Source=:memory:  Multiple creation

### ISSUE THREAD

**Issue by lingy-Mg** [msallin/SQLiteCodeFirst#127] opened 2018-06-09 23:39 UTC
![image](https://user-images.githubusercontent.com/4111244/41196992-68df047c-6c81-11e8-81e2-53e5a63379ee.png)

**Comment by lingy-Mg** [comment] 2018-06-09 23:40
At more than one time there will be an error

**Comment by lingy-Mg** [comment] 2018-06-10 00:04
OnModelCreating runs only once

**Comment by msallin** [comment] 2018-07-02 12:36
Hi

Please 
1) Write a more detailed description (I do not understand the problem).
2) Create a small demo project to reproduce the issue and upload it.

Thx

**Comment by IceBlizz6** [comment] 2018-07-21 11:22
Is the issue that it won't create tables in memory?
Been sitting with this problem for a while now. Changing connection string back and forth i think the furthest i've come is the error message:
SQLiteException: SQL logic error
no such table: History_82c009b41631-48579635f1ff64eb62d9

The same code works just fine with Data Source=Test.db
But based on the error message it looks like it does not create any tables with Data Source=:memory:

Would be really nice with a quick fix on this. Memory databases are invaluable for unit testing

**Comment by IceBlizz6** [comment] 2018-07-22 11:13
Okay so i downloaded the project and did a bit of testing. 
Your MemoryDbTest.CreateInMemoryDatabaseTest() works fine BUT only if it runs alone and only once.
If you copy the test and run both MemoryDbTest.CreateInMemoryDatabaseTest() and MemoryDbTest.CreateInMemoryDatabaseTest2() then the second one to run will always fail.

And the error message will always be complaining about missing tables: "no such table: Coaches".
Now i'm starting to understand the title "Data Source=:memory: Multiple creation", he's talking about running multiple in-memory databases.

This is a weird issue as the first test should be disposing of the memory database after the run and should not have an impact on the second test in the sequence.

**Comment by IceBlizz6** [comment] 2018-07-22 11:27
Ok so for anyone looking for a dirty fix:
On the first instance of DbContext in your test method make a call to context.Database.Initialize(true);

using (var context = new FootballDbContext(connection, false))
                {
                    context.Database.Initialize(true);
                    ......
               }

**Comment by IceBlizz6** [comment] 2018-07-22 11:49
If you want a bit nicer setup for tests you could do the following:

private bool dbInitialized;

        private DbConnection Connection { get; set; }

        private Func<FootballDbContext> DbContext
        {
            get
            {
                return () =>
                {
                    var context = new FootballDbContext(Connection, false);
                    if (!dbInitialized)
                    {
                        context.Database.Initialize(true);
                        dbInitialized = true;
                    }
                    return context;
                };
                
            }
        }

        [TestInitialize]
        public void Initialize()
        {
            Connection = new SQLiteConnection("data source=:memory:");

            // This is important! Else the in memory database will not work.
            Connection.Open();

            dbInitialized = false;
        }

        [TestCleanup]
        public void Cleanup()
        {
            Connection.Dispose();
        }

and simply use as: 

using (var context = DbContext())
 {
   ...........
}

Now it will detect the first call to create your DbContext and call Database.Initialize
Bonus points for moving this to an abstract class and make your test classes inherit from it.

**Comment by msallin** [comment] 2018-07-31 18:10
@IceBlizz6 thx!
Here we go: https://github.com/msallin/SQLiteCodeFirst/pull/131/files

@q349980363: Use the class `InMemoryDbTest<TDbContext>` as base class for your test (or adjust it for your needs).

**Closed as completed by msallin** 2018-07-31 18:10 UTC
Labels: To Analyse

**Comment by IceBlizz6** [comment] 2018-07-31 18:16
Hey
Sorry to say my "fix" was not really intended to be a permanent one.
Someone may want to use an actual in-memory database in their application outside of unit testing.
Is it possible to get a better more permanent fix that does not make us having to change they way we retrieve our DbContext?

**Comment by msallin** [comment] 2018-08-01 06:29
Unfortunately, it seems like this is not a problem with this library.
The `InitializeDatabase` method of the `IDatabaseInitializer` gets called only once by the entity framework, when using a sqlite in memory db, also if the db is new.
See e.g. here: https://stackoverflow.com/questions/43884181/in-memory-sqlite-and-database-disappearing
